# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Frank's Blog
email: fdezmero@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Frank. I know a bit about creating world-class digital products and even developing them. Here are some of my thoughts and dreams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.frankfdez.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: frank_fdez
github_username:  frafdez
lang: en-US # default lang
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Frank Fernández
  bio: >- # tell to the world
    Hi, I'm Frank. I know a bit about creating world-class digital products and even developing them. Here are some of my thoughts and dreams.
  username: username # general username
  twitter: https://x.com/frank_fdez
  email: mailto:fdezmero@gmail.com
  whatsapp: https://wa.me/34676091765
  linkedin: https://www.linkedin.com/in/frankfdez/
  avatar: /assets/img/avatar.jpeg # change with your own avatar


# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec


jekyll_admin:
  homepage: "posts"

collections:
  posts:
    output: true
    sidebar_label: News